["~/.config/helix/config.toml".key_value_present.editor]
line-number = "relative"
mouse = true
true-color = true

["~/.config/helix/config.toml".key_value_present.editor.file-picker]
hidden = false

["~/.config/helix/config.toml".key_value_present.editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

["~/.config/helix/config.toml".key_value_present.editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "hint"

["~/.config/helix/config.toml".key_value_present.editor.lsp]
display-inlay-hints = true

["~/.config/helix/config.toml".key_value_present.editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[["~/.bashrc".lines_present]]
__marker__ = "# Helix"
__lines__ = "export EDITOR=hx"
