[[key_value_present]]
file = "~/.config/helix/config.toml"

[[key_value_present.key.editor]]
line-number = "relative"
mouse = true
true-color = true

[[key_value_present.editor.file-picker]]
hidden = false

[[key_value_present.editor.soft-wrap]]
enable = true
max-wrap = 25         # increase value to reduce forced mid-word wrapping
max-indent-retain = 0

[[key_value_present.editor.inline-diagnostics]]
cursor-line = "hint"
other-lines = "hint"

[[key_value_present.editor.lsp]]
display-inlay-hints = true

[[key_value_present.editor.cursor-shape]]
insert = "bar"
normal = "block"
select = "underline"

[[lines_present]]
file = "~/.bashrc"
marker = "# Default editor"
lines = "export EDITOR=hx"
