[[lines_present]]
file = "~/config/nvim/init.lua"
lines = """
require("config.icons")
require("config.lazy")
require("config.keymaps")
require("config.autocmds")
require("config.options")
"""

[[key_value_present]]
file = "~/.config/nvim/lazyvim.json"
key.version = 8
key.news.'NEWS.md': "10960"
key.extras = []

[[entry_present]]
file = "~/.config/nvim/lazyvim.json"
entry.extras = [
    "lazyvim.plugins.extras.coding.luasnip",
    "lazyvim.plugins.extras.coding.mini-surround",
    "lazyvim.plugins.extras.coding.yanky",
    "lazyvim.plugins.extras.editor.illuminate",
    "lazyvim.plugins.extras.editor.refactoring",
    "lazyvim.plugins.extras.editor.telescope",
    "lazyvim.plugins.extras.formatting.prettier",
    "lazyvim.plugins.extras.linting.eslint",
    "lazyvim.plugins.extras.test.core",
    "lazyvim.plugins.extras.ui.treesitter-context"
  ]
